FROM node:20-slim

WORKDIR /app

COPY package*.json ./
RUN npm install
RUN npm install -g drizzle-kit

COPY . .

RUN apt-get update && apt-get install -y netcat-openbsd

EXPOSE 3333

ENTRYPOINT ["sh", "./entrypoint.sh"]
